---
- name: Deploy
  hosts: all
  vars:
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: "git@github.com:martinf08/projet-sardines.git"
    ansistrano_shared_files:
      - class/Config.php
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/after-symlink-shared-tasks.yml"
    ansistrano_keep_releases: 5
  roles:
    - ansistrano.deploy