---
- name: Deploy
  hosts: all
  vars:
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: "git@github.com:martinf08/projet-sardines.git"
    ansistrano_deploy_to: "/var/www/html"
    ansistrano_shared_files:
      - class/Config.php
  roles:
    - ansistrano.deploy